name: q_and_a_widget_example # The name of the example application.
description: Demonstrates how to use the q_and_a_widget package. # A description for the example app.
publish_to: 'none' # Prevents this example application from being published to pub.dev.

environment:
  sdk: '>=3.0.0 <4.0.0' # The Dart SDK version range supported by this example app.

dependencies:
  flutter:
    sdk: flutter # Declares Flutter SDK as a dependency.
  q_and_a_widget: # This is the dependency on your local package.
    path: ../ # Specifies the local path to your q_and_a_widget package.

dev_dependencies:
  flutter_test:
    sdk: flutter # Dependency for writing Flutter unit and widget tests for the example app.
  flutter_lints: ^2.0.0 # Provides lint rules for code quality in the example app.
