name: q_and_a_widget # Name of the package
description: A Flutter package for displaying questions with radio button choices, following MVVM architecture.
version: 0.0.1 # Initial version number of the package
homepage: https://github.com/yemreeee/q_and_a_widget # Homepage URL for the package

environment:
  sdk: '>=3.0.0 <4.0.0' # Supported Dart SDK range
  flutter: ">=1.17.0" # Supported Flutter SDK range

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Recommended lint rules for code quality
